### ISSUE TITLE
Semantic Highlighting

### ISSUE THREAD

**Issue by stefan-sedlak** [ryanolsonx/vscode-solarized-theme#2]
Hi @ryanolsonx ,
thanks for great theme! I tried all solarized-dark themes for vscode and your is the best 😎

Any plans to support [semantic highlighting](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview)?

**Comment by ryanolsonx** [comment]
Thanks! I appreciate that. I’ll look into it.

**Comment by ryanolsonx** [comment]
No plans to support it right now
