### ISSUE TITLE
Upload to Open VSX

### ISSUE THREAD

**Issue by matejdro** [ryanolsonx/vscode-solarized-theme#5]
Open source builds of VS Code on some Linux distribution use Open VSX instead of VS marketplace to install extensions: https://bugs.archlinux.org/task/67780

Any chance you could upload this extension to Open VSX?

Thanks.

**Comment by ryanolsonx** [comment]
Sure! (sorry for the very late reply)

**Comment by ryanolsonx** [comment]
I tried... not easy.

**Comment by dancollins** [comment]
I was able to use the following URL to download the VSIX and install into Cursor. Thanks for making my favourite theme :)

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ryanolsonx/vsextensions/solarized/2.6.0/vspackage
