### ISSUE TITLE
support for bracket highlight colors in vscode 1.67

### ISSUE THREAD

**Issue by vagusX** [ryanolsonx/vscode-solarized-theme#7]
![image](https://user-images.githubusercontent.com/6828924/167329593-26205c3d-c548-4d05-abc1-b1f17dd99055.png)

**Comment by kuflash** [comment]
@ryanolsonx for me, it would be cool use colors from example of readme
<img width="600" alt="image" src="https://user-images.githubusercontent.com/815876/168021217-c0d57d86-3ca1-4709-96ca-f6f49e67d8a1.png">

If I'm understand, brackets color should be equals with text color

**Comment by kuflash** [comment]
But I'm understand, that problem is cause by new VSCode feature - [colorizedBracketPairs](https://code.visualstudio.com/updates/v1_62#_customizable-bracket-pairs). And if turn off this setting, brackets color will be correct:

```
"editor.language.colorizedBracketPairs": []
```

**Comment by ryanolsonx** [comment]
Ok! I’ll look into this soon. I’m swamped at work and so it might be several days. If you want to experient, I’m open to PRs.

**Comment by dessant** [comment]
If `"editor.language.colorizedBracketPairs": []` is set, matching bracket pairs are no longer highlighted when the cursor is next to them.

**Comment by ryanolsonx** [comment]
Released to the marketplace (version 2.1.0)
